### ISSUE TITLE
Need to import GraphiQl namespace since GraphiQL 1.2.0

### ISSUE THREAD

**Issue by Cito** [JosephWoodward/graphiql-dotnet#28]
Adding the `app.UseGraphiQl()` middleware does not seem to work in GraphiQL 1.2.0 unless you add `using GraphiQl` to `Startup.cs`. In version 1.1.0 it this does not seem to be necessary. This should be explicitly mentioned in the README and also added to the graphiql.example, if it's not considered a regression.

**Comment by josephwoodward** [comment]
@Cito Thanks for bringing this to my attention.

Do you not get a compilation error if the namespace isn't imported?
